In [1]:
# Data manipulation
import numpy as np

#Data Exploratiion
import pandas as pd

#Data Visualization
import matplotlib.pyplot as plt
%matplotlib inline

In [18]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from Data_Filter_for_model_selection import getFinalData

In [3]:
from Principle_component_analysis_main import performPCA,getConfusionMatrix,getVisuals

In [4]:
crimes_pred_data = getFinalData()

In [5]:
# Target variable as Morning

data = crimes_pred_data.drop(['PD_DESC','CRM_ATPT_CPTD_CD','Precinct','Time','Afternoon','Evening','Night'],axis=1)
labelencoder_X = LabelEncoder()
data['OFNS_DESC'] = labelencoder_X.fit_transform(data['OFNS_DESC'])
data['PREM_TYP_DESC'] = labelencoder_X.fit_transform(data['PREM_TYP_DESC'])
data['LAW_CAT_CD'] = labelencoder_X.fit_transform(data['LAW_CAT_CD'])
data['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(data['LOC_OF_OCCUR_DESC'])
data['Morning'] = labelencoder_X.fit_transform(data['Morning'])
    
X = data.iloc[:, 0:4].values
Y = data.iloc[:, 4].values
  
# perform Principle Component Analysis
split_data_morn = performPCA(X,Y)

#Compute Confusion Matrix
getConfusionMatrix(split_data_morn)



P:\Anaconda\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


The Variance is [0.34866883 0.25363372]
Accuracy: 0.7816920943134535

Confusion Matrix is as follows
[[8454    0]
 [2361    0]]


In [6]:
#Target Variable as Afternoon
data = crimes_pred_data.drop(['PD_DESC','CRM_ATPT_CPTD_CD','Precinct','Time','Morning','Evening','Night'],axis=1)
labelencoder_X = LabelEncoder()
data['OFNS_DESC'] = labelencoder_X.fit_transform(data['OFNS_DESC'])
data['PREM_TYP_DESC'] = labelencoder_X.fit_transform(data['PREM_TYP_DESC'])
data['LAW_CAT_CD'] = labelencoder_X.fit_transform(data['LAW_CAT_CD'])
data['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(data['LOC_OF_OCCUR_DESC'])
data['Afternoon'] = labelencoder_X.fit_transform(data['Afternoon'])

X_noon = data.iloc[:, 0:4].values
Y_noon = data.iloc[:, 4].values

# perform Principle Component Analysis
split_data_noon = performPCA(X_noon,Y_noon)

#Compute Confusion Matrix
getConfusionMatrix(split_data_noon)


The Variance is [0.34866883 0.25363372]
Accuracy: 0.8355062413314841

Confusion Matrix is as follows
[[9036    0]
 [1779    0]]


P:\Anaconda\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [7]:
#Target Variable as Evening
data = crimes_pred_data.drop(['PD_DESC','CRM_ATPT_CPTD_CD','Precinct','Time','Morning','Afternoon','Night'],axis=1)
labelencoder_X = LabelEncoder()
data['OFNS_DESC'] = labelencoder_X.fit_transform(data['OFNS_DESC'])
data['PREM_TYP_DESC'] = labelencoder_X.fit_transform(data['PREM_TYP_DESC'])
data['LAW_CAT_CD'] = labelencoder_X.fit_transform(data['LAW_CAT_CD'])
data['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(data['LOC_OF_OCCUR_DESC'])
data['Evening'] = labelencoder_X.fit_transform(data['Evening'])
    
X_eve = data.iloc[:, 0:4].values
Y_eve = data.iloc[:, 4].values

# perform Principle Component Analysis
split_data_eve = performPCA(X_eve,Y_eve)

#Compute Confusion Matrix
getConfusionMatrix(split_data_eve)


The Variance is [0.34866883 0.25363372]
Accuracy: 0.8748035136384651

Confusion Matrix is as follows
[[9461    0]
 [1354    0]]


P:\Anaconda\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [8]:
#Target Variable as Night

data = crimes_pred_data.drop(['PD_DESC','CRM_ATPT_CPTD_CD','Precinct','Time','Morning','Afternoon','Evening'],axis=1)
labelencoder_X = LabelEncoder()
data['OFNS_DESC'] = labelencoder_X.fit_transform(data['OFNS_DESC'])
data['PREM_TYP_DESC'] = labelencoder_X.fit_transform(data['PREM_TYP_DESC'])
data['LAW_CAT_CD'] = labelencoder_X.fit_transform(data['LAW_CAT_CD'])
data['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(data['LOC_OF_OCCUR_DESC'])
data['Night'] = labelencoder_X.fit_transform(data['Night'])
    
X_night = data.iloc[:, 0:4].values
Y_night = data.iloc[:, 4].values

# perform Principle Component Analysis
split_data_night = performPCA(X_night,Y_night)

#Compute Confusion Matrix
getConfusionMatrix(split_data_night)


The Variance is [0.34866883 0.25363372]
Accuracy: 0.8940360610263522

Confusion Matrix is as follows
[[9669    0]
 [1146    0]]


P:\Anaconda\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [11]:
#Target Variable as OFNS_DESC
data = crimes_pred_data.drop(['PD_DESC','OFNS_DESC','CRM_ATPT_CPTD_CD','Precinct','Time'],axis=1)
labelencoder_X = LabelEncoder()
data['PREM_TYP_DESC'] = labelencoder_X.fit_transform(data['PREM_TYP_DESC'])
data['LAW_CAT_CD'] = labelencoder_X.fit_transform(data['LAW_CAT_CD'])
data['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(data['LOC_OF_OCCUR_DESC'])
data['Morning'] = labelencoder_X.fit_transform(data['Morning'])
data['Afternoon'] = labelencoder_X.fit_transform(data['Afternoon'])
data['Evening'] = labelencoder_X.fit_transform(data['Evening'])
data['Night'] = labelencoder_X.fit_transform(data['Night'])

data_ofns = crimes_pred_data.copy()
data_ofns.reset_index(drop=True, inplace=True)
data_ofns = data_ofns.drop(['PD_DESC','PREM_TYP_DESC','LAW_CAT_CD','LOC_OF_OCCUR_DESC','CRM_ATPT_CPTD_CD','Precinct','Time','Morning','Afternoon','Evening','Night'],axis=1)
    
    
X_ofns = data.iloc[:, 0:7].values
data_ofns['OFNS_DESC'] = labelencoder_X.fit_transform(data_ofns['OFNS_DESC'])
Y_ofns = data_ofns['OFNS_DESC']

# perform Principle Component Analysis
split_data_ofns = performPCA(X_ofns,Y_ofns)

#Compute Confusion Matrix
getConfusionMatrix(split_data_ofns)


The Variance is [0.18336729 0.16921799]
Accuracy: 0.5774387424872862

Confusion Matrix is as follows
[[2223 1304    0]
 [ 776 4022    0]
 [ 826 1664    0]]


P:\Anaconda\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [12]:
#Target Variable as Premises
data = crimes_pred_data.drop(['PD_DESC','PREM_TYP_DESC','CRM_ATPT_CPTD_CD','Precinct','Time'],axis=1)
labelencoder_X = LabelEncoder()
data['OFNS_DESC'] = labelencoder_X.fit_transform(data['OFNS_DESC'])
data['LAW_CAT_CD'] = labelencoder_X.fit_transform(data['LAW_CAT_CD'])
data['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(data['LOC_OF_OCCUR_DESC'])
data['Morning'] = labelencoder_X.fit_transform(data['Morning'])
data['Afternoon'] = labelencoder_X.fit_transform(data['Afternoon'])
data['Evening'] = labelencoder_X.fit_transform(data['Evening'])
data['Night'] = labelencoder_X.fit_transform(data['Night'])

data_ofns = crimes_pred_data.copy()
data_ofns.reset_index(drop=True, inplace=True)
data_ofns = data_ofns.drop(['PD_DESC','OFNS_DESC','LAW_CAT_CD','LOC_OF_OCCUR_DESC','CRM_ATPT_CPTD_CD','Precinct','Time','Morning','Afternoon','Evening','Night'],axis=1)
    
    
X_ofns = data.iloc[:, 0:7].values
data_ofns['PREM_TYP_DESC'] = labelencoder_X.fit_transform(data_ofns['PREM_TYP_DESC'])
Y_ofns = data_ofns['PREM_TYP_DESC']

# perform Principle Component Analysis
split_data_ofns = performPCA(X_ofns,Y_ofns)

#Compute Confusion Matrix
getConfusionMatrix(split_data_ofns)

The Variance is [0.17825909 0.16682529]
Accuracy: 0.6338418862690708

Confusion Matrix is as follows
[[   0    0 3398]
 [   0    0  562]
 [   0    0 6855]]


P:\Anaconda\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [14]:
#Target Variable as Intensity of Crime
data = crimes_pred_data.drop(['PD_DESC','LAW_CAT_CD','CRM_ATPT_CPTD_CD','Precinct','Time'],axis=1)
labelencoder_X = LabelEncoder()
data['OFNS_DESC'] = labelencoder_X.fit_transform(data['OFNS_DESC'])
data['PREM_TYP_DESC'] = labelencoder_X.fit_transform(data['PREM_TYP_DESC'])
data['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(data['LOC_OF_OCCUR_DESC'])
data['Morning'] = labelencoder_X.fit_transform(data['Morning'])
data['Afternoon'] = labelencoder_X.fit_transform(data['Afternoon'])
data['Evening'] = labelencoder_X.fit_transform(data['Evening'])
data['Night'] = labelencoder_X.fit_transform(data['Night'])

data_ofns = crimes_pred_data.copy()
data_ofns.reset_index(drop=True, inplace=True)
data_ofns = data_ofns.drop(['PD_DESC','OFNS_DESC','PREM_TYP_DESC','LOC_OF_OCCUR_DESC','CRM_ATPT_CPTD_CD','Precinct','Time','Morning','Afternoon','Evening','Night'],axis=1)
    
    
X_ofns = data.iloc[:, 0:7].values
data_ofns['LAW_CAT_CD'] = labelencoder_X.fit_transform(data_ofns['LAW_CAT_CD'])
Y_ofns = data_ofns['LAW_CAT_CD']

# perform Principle Component Analysis
split_data_ofns = performPCA(X_ofns,Y_ofns)

#Compute Confusion Matrix
getConfusionMatrix(split_data_ofns)

The Variance is [0.19834576 0.17557375]
Accuracy: 0.9249190938511327

Confusion Matrix is as follows
[[    0   812]
 [    0 10003]]


P:\Anaconda\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [17]:
#Target Variable as Location of Occurence
data = crimes_pred_data.drop(['PD_DESC','LOC_OF_OCCUR_DESC','CRM_ATPT_CPTD_CD','Precinct','Time'],axis=1)
labelencoder_X = LabelEncoder()
data['OFNS_DESC'] = labelencoder_X.fit_transform(data['OFNS_DESC'])
data['LAW_CAT_CD'] = labelencoder_X.fit_transform(data['LAW_CAT_CD'])
data['PREM_TYP_DESC'] = labelencoder_X.fit_transform(data['PREM_TYP_DESC'])
data['Morning'] = labelencoder_X.fit_transform(data['Morning'])
data['Afternoon'] = labelencoder_X.fit_transform(data['Afternoon'])
data['Evening'] = labelencoder_X.fit_transform(data['Evening'])
data['Night'] = labelencoder_X.fit_transform(data['Night'])

data_ofns = crimes_pred_data.copy()
data_ofns.reset_index(drop=True, inplace=True)
data_ofns = data_ofns.drop(['PD_DESC','OFNS_DESC','PREM_TYP_DESC','LAW_CAT_CD','CRM_ATPT_CPTD_CD','Precinct','Time','Morning','Afternoon','Evening','Night'],axis=1)
    
    
X_ofns = data.iloc[:, 0:7].values
data_ofns['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(data_ofns['LOC_OF_OCCUR_DESC'])
Y_ofns = data_ofns['LOC_OF_OCCUR_DESC']

# perform Principle Component Analysis
split_data_ofns = performPCA(X_ofns,Y_ofns)

#Compute Confusion Matrix
getConfusionMatrix(split_data_ofns)

The Variance is [0.19619752 0.17648708]
Accuracy: 0.7061488673139159

Confusion Matrix is as follows
[[   0 2621    0    0]
 [   0 7637    0    0]
 [   0  392    0    0]
 [   0  165    0    0]]


P:\Anaconda\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
