In [1]:
# Data manipulation
import numpy as np

#Data Exploratiion
import pandas as pd

#Data Visualization
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from Data_Filter_for_model_selection import getFinalData

0.0
0.0
0.0
0.0
0.0
<class 'pandas.core.frame.DataFrame'>
Int64Index: 5835784 entries, 1 to 6039728
Data columns (total 16 columns):
CMPLNT_FR_DT         object
CMPLNT_FR_TM         object
CMPLNT_TO_DT         object
CMPLNT_TO_TM         object
RPT_DT               object
OFNS_DESC            object
PD_DESC              object
CRM_ATPT_CPTD_CD     object
LAW_CAT_CD           object
BORO_NM              object
ADDR_PCT_CD          float64
LOC_OF_OCCUR_DESC    object
PREM_TYP_DESC        object
Latitude             float64
Longitude            float64
Lat_Lon              object
dtypes: float64(3), object(13)
memory usage: 756.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 4 columns):
Shape_Area    77 non-null float64
Shape_Leng    77 non-null float64
Precinct      77 non-null int64
the_geom      77 non-null object
dtypes: float64(2), int64(1), object(1)
memory usage: 2.5+ KB


In [3]:
from Principle_component_analysis_main import performPCA,getConfusionMatrixNB,getVisuals

In [4]:
crimes_pred_data = getFinalData()

In [5]:
crimes_pred_data.head()

OFNS_DESC  \
StartTime                                           
2014-03-30 20:40:00               DANGEROUS DRUGS   
2015-12-31 19:45:00  ASSAULT 3 & RELATED OFFENSES   
2015-12-31 17:15:00  ASSAULT 3 & RELATED OFFENSES   
2015-12-31 10:30:00  ASSAULT 3 & RELATED OFFENSES   
2015-12-31 00:23:00  ASSAULT 3 & RELATED OFFENSES   

                                            PD_DESC CRM_ATPT_CPTD_CD  \
StartTime                                                              
2014-03-30 20:40:00  CONTROLLED SUBSTANCE,INTENT TO        ATTEMPTED   
2015-12-31 19:45:00                       ASSAULT 3        COMPLETED   
2015-12-31 17:15:00                       ASSAULT 3        COMPLETED   
2015-12-31 10:30:00           MENACING,UNCLASSIFIED        COMPLETED   
2015-12-31 00:23:00                       ASSAULT 3        COMPLETED   

                      LAW_CAT_CD BORO_NM LOC_OF_OCCUR_DESC  \
StartTime                                                    
2014-03-30 20:40:00       FELONY   BRONX            INSIDE   
2015-12-31 19:45:00  MISDEMEANOR   BRONX            INSIDE   
2015-12-31 17:15:00  MISDEMEANOR   BRONX            INSIDE   
2015-12-31 10:30:00  MISDEMEANOR   BRONX            INSIDE   
2015-12-31 00:23:00  MISDEMEANOR   BRONX            INSIDE   

                              PREM_TYP_DESC  Precinct  Time  Morning  \
StartTime                                                              
2014-03-30 20:40:00  RESIDENCE - APT. HOUSE        44  20.0    False   
2015-12-31 19:45:00                  STREET        44  19.0    False   
2015-12-31 17:15:00  RESIDENCE - APT. HOUSE        44  17.0    False   
2015-12-31 10:30:00  RESIDENCE - APT. HOUSE        44  10.0     True   
2015-12-31 00:23:00                  STREET        44   0.0     True   

                     Afternoon  Evening  Night  
StartTime                                       
2014-03-30 20:40:00      False     True  False  
2015-12-31 19:45:00      False     True  False  
2015-12-31 17:15:00       True    False  False  
2015-12-31 10:30:00      False    False  False  
2015-12-31 00:23:00      False    False  False

In [6]:
crimes_pred_data['Night'].value_counts()

False    38687
True      4572
Name: Night, dtype: int64

In [23]:
# Target variable as Morning

data_morn = crimes_pred_data.drop(['PD_DESC','CRM_ATPT_CPTD_CD','BORO_NM','Precinct','Time','Afternoon','Evening','Night'],axis=1)
labelencoder_X = LabelEncoder()
data_morn['OFNS_DESC'] = labelencoder_X.fit_transform(data_morn['OFNS_DESC'])
data_morn['PREM_TYP_DESC'] = labelencoder_X.fit_transform(data_morn['PREM_TYP_DESC'])
data_morn['LAW_CAT_CD'] = labelencoder_X.fit_transform(data_morn['LAW_CAT_CD'])
data_morn['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(data_morn['LOC_OF_OCCUR_DESC'])
data_morn['Morning'] = labelencoder_X.fit_transform(data_morn['Morning'])
    
X_morn = data_morn.iloc[:, 0:4].values
Y_morn = data_morn.iloc[:, 4].values
  
# perform Principle Component Analysis
split_data_morn = performPCA(X_morn,Y_morn)

#Compute Confusion Matrix
classifier = getConfusionMatrixNB(split_data_morn)

#Plot Training Set
getVisuals(split_data_morn[0],split_data_morn[2],classifier,'Morning', 'Logistic Regression (Training Set)')


The Variance is [0.34866883 0.25363372]
Accuracy: 0.7816920943134535

Confusion Matrix is as follows
[[8454    0]
 [2361    0]]


C:\Users\wilfr\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


AttributeError: 'NoneType' object has no attribute 'predict'

In [12]:
#Target Variable as Afternoon
data = crimes_pred_data.drop(['PD_DESC','CRM_ATPT_CPTD_CD','BORO_NM','Precinct','Time','Morning','Evening','Night'],axis=1)
labelencoder_X = LabelEncoder()
data['OFNS_DESC'] = labelencoder_X.fit_transform(data['OFNS_DESC'])
data['PREM_TYP_DESC'] = labelencoder_X.fit_transform(data['PREM_TYP_DESC'])
data['LAW_CAT_CD'] = labelencoder_X.fit_transform(data['LAW_CAT_CD'])
data['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(data['LOC_OF_OCCUR_DESC'])
data['Afternoon'] = labelencoder_X.fit_transform(data['Afternoon'])
    
X_noon = data.iloc[:, 0:4].values
Y_noon = data.iloc[:, 4].values

# perform Principle Component Analysis
split_data_noon = performPCA(X_noon,Y_noon)

#Compute Confusion Matrix
getConfusionMatrixNB(split_data_noon)

The Variance is [0.34866883 0.25363372]
Accuracy: 0.8355062413314841

Confusion Matrix is as follows
[[9036    0]
 [1779    0]]


C:\Users\wilfr\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [13]:
#Target Variable as Evening
data = crimes_pred_data.drop(['PD_DESC','CRM_ATPT_CPTD_CD','BORO_NM','Precinct','Time','Morning','Afternoon','Night'],axis=1)
labelencoder_X = LabelEncoder()
data['OFNS_DESC'] = labelencoder_X.fit_transform(data['OFNS_DESC'])
data['PREM_TYP_DESC'] = labelencoder_X.fit_transform(data['PREM_TYP_DESC'])
data['LAW_CAT_CD'] = labelencoder_X.fit_transform(data['LAW_CAT_CD'])
data['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(data['LOC_OF_OCCUR_DESC'])
data['Evening'] = labelencoder_X.fit_transform(data['Evening'])
    
X_eve = data.iloc[:, 0:4].values
Y_eve = data.iloc[:, 4].values

# perform Principle Component Analysis
split_data_eve = performPCA(X_eve,Y_eve)

#Compute Confusion Matrix
getConfusionMatrixNB(split_data_eve)

The Variance is [0.34866883 0.25363372]
Accuracy: 0.874711049468331

Confusion Matrix is as follows
[[9457    4]
 [1351    3]]


C:\Users\wilfr\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [14]:
#Target Variable as Night
data = crimes_pred_data.drop(['PD_DESC','CRM_ATPT_CPTD_CD','BORO_NM','Precinct','Time','Morning','Afternoon','Evening'],axis=1)
labelencoder_X = LabelEncoder()
data['OFNS_DESC'] = labelencoder_X.fit_transform(data['OFNS_DESC'])
data['PREM_TYP_DESC'] = labelencoder_X.fit_transform(data['PREM_TYP_DESC'])
data['LAW_CAT_CD'] = labelencoder_X.fit_transform(data['LAW_CAT_CD'])
data['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(data['LOC_OF_OCCUR_DESC'])
data['Night'] = labelencoder_X.fit_transform(data['Night'])
    
X_night = data.iloc[:, 0:4].values
Y_night = data.iloc[:, 4].values

# perform Principle Component Analysis
split_data_night = performPCA(X_night,Y_night)

#Compute Confusion Matrix
getConfusionMatrixNB(split_data_night)

The Variance is [0.34866883 0.25363372]
Accuracy: 0.8940360610263522

Confusion Matrix is as follows
[[9669    0]
 [1146    0]]


C:\Users\wilfr\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [18]:
#Target Variable as Ofns_desc
data = crimes_pred_data.drop(['OFNS_DESC','PD_DESC','CRM_ATPT_CPTD_CD','Precinct','Time','BORO_NM'],axis=1)
labelencoder_X = LabelEncoder()
#data['OFNS_DESC'] = labelencoder_X.fit_transform(data['OFNS_DESC'])
data['PREM_TYP_DESC'] = labelencoder_X.fit_transform(data['PREM_TYP_DESC'])
data['LAW_CAT_CD'] = labelencoder_X.fit_transform(data['LAW_CAT_CD'])
data['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(data['LOC_OF_OCCUR_DESC'])
data['Morning'] = labelencoder_X.fit_transform(data['Morning'])
data['Afternoon'] = labelencoder_X.fit_transform(data['Afternoon'])
data['Evening'] = labelencoder_X.fit_transform(data['Evening'])
data['Night'] = labelencoder_X.fit_transform(data['Night'])
    
dataY = crimes_pred_data.copy()
dataY = dataY.drop(['PD_DESC','CRM_ATPT_CPTD_CD','Precinct','Time','Morning','Afternoon','Evening','BORO_NM','LAW_CAT_CD','LOC_OF_OCCUR_DESC','PREM_TYP_DESC','Night'],axis=1)
#dataY.head()
dataY['OFNS_DESC'] = labelencoder_X.fit_transform(dataY['OFNS_DESC'])

X_ofns = data.iloc[:, 0:7].values
Y_ofns = dataY.iloc[:,0].values

# perform Principle Component Analysis
split_data_ofns = performPCA(X_ofns,Y_ofns)

#Compute Confusion Matrix
getConfusionMatrixNB(split_data_ofns)

The Variance is [0.18336729 0.16921799]
Accuracy: 0.5757743874248729

Confusion Matrix is as follows
[[2176 1351    0]
 [ 747 4051    0]
 [ 810 1680    0]]


C:\Users\wilfr\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [20]:
#Target Variable as PREM_TYP_DESC
data = crimes_pred_data.drop(['PREM_TYP_DESC','PD_DESC','CRM_ATPT_CPTD_CD','Precinct','Time','BORO_NM'],axis=1)
labelencoder_X = LabelEncoder()
data['OFNS_DESC'] = labelencoder_X.fit_transform(data['OFNS_DESC'])
#data['PREM_TYP_DESC'] = labelencoder_X.fit_transform(data['PREM_TYP_DESC'])
data['LAW_CAT_CD'] = labelencoder_X.fit_transform(data['LAW_CAT_CD'])
data['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(data['LOC_OF_OCCUR_DESC'])
data['Morning'] = labelencoder_X.fit_transform(data['Morning'])
data['Afternoon'] = labelencoder_X.fit_transform(data['Afternoon'])
data['Evening'] = labelencoder_X.fit_transform(data['Evening'])
data['Night'] = labelencoder_X.fit_transform(data['Night'])
    
dataY = crimes_pred_data.copy()
dataY = dataY.drop(['PD_DESC','CRM_ATPT_CPTD_CD','Precinct','Time','Morning','Afternoon','Evening','BORO_NM','LAW_CAT_CD','LOC_OF_OCCUR_DESC','OFNS_DESC','Night'],axis=1)
#dataY.head()
dataY['PREM_TYP_DESC'] = labelencoder_X.fit_transform(dataY['PREM_TYP_DESC'])

X_prem = data.iloc[:, 0:7].values
Y_prem = dataY.iloc[:,0].values

# perform Principle Component Analysis
split_data_prem = performPCA(X_prem,Y_prem)

#Compute Confusion Matrix
getConfusionMatrixNB(split_data_prem)

The Variance is [0.17825909 0.16682529]
Accuracy: 0.6338418862690708

Confusion Matrix is as follows
[[   0    0 3398]
 [   0    0  562]
 [   0    0 6855]]


C:\Users\wilfr\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [21]:
#Target Variable as LAW_CAT_CD
data = crimes_pred_data.drop(['LAW_CAT_CD','PD_DESC','CRM_ATPT_CPTD_CD','Precinct','Time','BORO_NM'],axis=1)
labelencoder_X = LabelEncoder()
data['OFNS_DESC'] = labelencoder_X.fit_transform(data['OFNS_DESC'])
data['PREM_TYP_DESC'] = labelencoder_X.fit_transform(data['PREM_TYP_DESC'])
#data['LAW_CAT_CD'] = labelencoder_X.fit_transform(data['LAW_CAT_CD'])
data['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(data['LOC_OF_OCCUR_DESC'])
data['Morning'] = labelencoder_X.fit_transform(data['Morning'])
data['Afternoon'] = labelencoder_X.fit_transform(data['Afternoon'])
data['Evening'] = labelencoder_X.fit_transform(data['Evening'])
data['Night'] = labelencoder_X.fit_transform(data['Night'])
    
dataY = crimes_pred_data.copy()
dataY = dataY.drop(['PD_DESC','CRM_ATPT_CPTD_CD','Precinct','Time','Morning','Afternoon','Evening','BORO_NM','PREM_TYP_DESC','LOC_OF_OCCUR_DESC','OFNS_DESC','Night'],axis=1)
#dataY.head()
dataY['LAW_CAT_CD'] = labelencoder_X.fit_transform(dataY['LAW_CAT_CD'])

X_law = data.iloc[:, 0:7].values
Y_law = dataY.iloc[:,0].values

# perform Principle Component Analysis
split_data_law = performPCA(X_law,Y_law)

#Compute Confusion Matrix
getConfusionMatrixNB(split_data_law)

The Variance is [0.19834576 0.17557375]
Accuracy: 0.9249190938511327

Confusion Matrix is as follows
[[    0   812]
 [    0 10003]]


C:\Users\wilfr\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [22]:
#Target Variable as LOC_OF_OCCUR_DESC
data = crimes_pred_data.drop(['LOC_OF_OCCUR_DESC','PD_DESC','CRM_ATPT_CPTD_CD','Precinct','Time','BORO_NM'],axis=1)
labelencoder_X = LabelEncoder()
data['OFNS_DESC'] = labelencoder_X.fit_transform(data['OFNS_DESC'])
data['PREM_TYP_DESC'] = labelencoder_X.fit_transform(data['PREM_TYP_DESC'])
data['LAW_CAT_CD'] = labelencoder_X.fit_transform(data['LAW_CAT_CD'])
#data['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(data['LOC_OF_OCCUR_DESC'])
data['Morning'] = labelencoder_X.fit_transform(data['Morning'])
data['Afternoon'] = labelencoder_X.fit_transform(data['Afternoon'])
data['Evening'] = labelencoder_X.fit_transform(data['Evening'])
data['Night'] = labelencoder_X.fit_transform(data['Night'])
    
dataY = crimes_pred_data.copy()
dataY = dataY.drop(['PD_DESC','CRM_ATPT_CPTD_CD','Precinct','Time','Morning','Afternoon','Evening','BORO_NM','PREM_TYP_DESC','LAW_CAT_CD','OFNS_DESC','Night'],axis=1)
#dataY.head()
dataY['LOC_OF_OCCUR_DESC'] = labelencoder_X.fit_transform(dataY['LOC_OF_OCCUR_DESC'])

X_loc = data.iloc[:, 0:7].values
Y_loc = dataY.iloc[:,0].values

# perform Principle Component Analysis
split_data_loc = performPCA(X_loc,Y_loc)

#Compute Confusion Matrix
getConfusionMatrixNB(split_data_loc)

The Variance is [0.19619752 0.17648708]
Accuracy: 0.7061488673139159

Confusion Matrix is as follows
[[   0 2621    0    0]
 [   0 7637    0    0]
 [   0  392    0    0]
 [   0  165    0    0]]


C:\Users\wilfr\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
